name: "Bump and Build"

on:
  workflow_call: {}

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:

  #############################################################################
  #                               BUMP VERSION                                #
  #############################################################################

  bump-version:
    runs-on: ubuntu-24.04

    outputs:
      new-tag: ${{ steps.next-version.outputs.new_tag }}

    steps:
    - name: "Checkout"
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: "Setup Cache"
      uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2

    - name: "Mise Install"
      uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1

    - name: "Generate GitHub App Token"
      id: github-app-token
      uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
      with:
        app-id: ${{ vars.SMYKLOT_APP_ID }}
        private-key: ${{ secrets.SMYKLOT_APP_PRIVATE_KEY }}

    - name: "Get GitHub App User ID"
      id: get-user-id
      env:
        APP_SLUG: ${{ steps.github-app-token.outputs.app-slug }}
        GH_TOKEN: ${{ steps.github-app-token.outputs.token }}
      run: echo "user-id=$(gh api "/users/${{ env.APP_SLUG }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"

    - name: "Set Commiter"
      env:
        APP_SLUG: ${{ steps.github-app-token.outputs.app-slug }}
        USER_ID: ${{ steps.get-user-id.outputs.user-id }}
      run: |
        git config --global user.name '${{ env.APP_SLUG }}[bot]'
        git config --global user.email '${{ env.USER_ID }}+${{ env.APP_SLUG }}[bot]@users.noreply.github.com'

    - name: "Calculate the Next Version"
      id: next-version
      uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
      with:
        github_token: ${{ steps.github-app-token.outputs.token }}
        dry_run: true

    - name: "Bump version in Cargo.toml"
      env:
        NEW_VERSION: ${{ steps.next-version.outputs.new_version }}
      run: .github/scripts/bump-cargo.bash

    - name: "Regenerate Documentation"
      run: |
        mise run clean::gen::docs::markdown ::: gen::docs::markdown

    - name: "Commit and tag new version"
      env:
        NEW_TAG: ${{ steps.next-version.outputs.new_tag }}
        GH_TOKEN: ${{ steps.github-app-token.outputs.token }}
      run: .github/scripts/commit-tag-version.bash

  #############################################################################
  #                               DEFINE MATRIX                               #
  #############################################################################

  define-matrix:
    runs-on: ubuntu-24.04

    outputs:
      matrix: ${{ steps.define-matrix.outputs.matrix }}

    steps:
    - name: "Define Matrix"
      id: define-matrix
      run: |
        echo "matrix=$(cat <<'EOF' | jq --compact-output .
          {
            "include": [
              {
                "name": "macos-arm64",
                "runner": "macos-15",
                "target": "aarch64-apple-darwin",
                "env": {
                  "OPENSSL_DIR": "/opt/homebrew/opt/openssl"
                }
              },
              {
                "name": "macos-amd64",
                "runner": "macos-15-intel",
                "target": "x86_64-apple-darwin",
                "env": {
                  "OPENSSL_DIR": "/usr/local/opt/openssl"
                }
              }
            ]
          }
        EOF
        )" >> "$GITHUB_OUTPUT"

  #############################################################################
  #                              BUILD ARTIFACTS                              #
  #############################################################################

  build-artifacts:
    runs-on: ${{ matrix.runner }}

    needs:
    - bump-version
    - define-matrix

    env:
      OPENSSL_DIR: ${{ matrix.env.OPENSSL_DIR }}

    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.define-matrix.outputs.matrix) }}

    steps:
    - name: "Checkout"
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: "Install Rust"
      uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561 # stable (uses major version tagging)
      with:
        targets: ${{ matrix.target }}
        toolchain: nightly

    - name: "Setup Cache"
      uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2

    - name: "Build macOS Binary"
      if: contains(matrix.target, 'darwin')
      run: |
        cargo +nightly build -Z unstable-options \
          --artifact-dir dist \
          --target ${{ matrix.target }} \
          --verbose \
          --locked \
          --release

    - name: "Add Arch Suffix to Binary"
      if: contains(matrix.target, 'darwin')
      id: add-suffix
      env:
        MATRIX_NAME: ${{ matrix.name }}
        BASE_PATH: dist/${{ github.event.repository.name }}
      run: |
        final_path="$BASE_PATH-$MATRIX_NAME"
        echo "binary_path=$final_path" >> "$GITHUB_OUTPUT"
        
        mv "$BASE_PATH" "$final_path"

    - name: "Upload ${{ matrix.name }} artifacts"
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      if: success()
      id: upload-artifacts
      with:
        name: ${{ github.event.repository.name }}-${{ matrix.name }}
        path: ${{ steps.add-suffix.outputs.binary_path }}
        if-no-files-found: error

    ################################# DEBUG #################################

    - name: "Initialize Debug Shell"
      if: vars.FORCE_DEBUG_SHELL == 'true' || failure() && runner.debug == '1'
      env:
        TUNSHELL_SECRET: ${{ secrets.TUNSHELL_SECRET }}
      run: .github/scripts/debug-shell.bash
